apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: kiali-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - kiali.istio.fun
    port:
      name: https-kiali
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: kiali-cert-dns